apiVersion: projectsame.io/v1alpha1
metadata:
    name: wikiqa
    version: 0.0.0
workflow:
    type: kubeflow
    parameters:
        kubeflowVersion: 1.2
        kubeflowNamespace: kubeflow # Only support Kubeflow namespace
        credentialFile: porter-kfp
pipeline:
    name: "wikiqa_pipeline"
    description: "WikiQA Question Answering through Transfer Learning"
    package: "src/wikiqa/pipeline.py"
run:
    name: "default"
    parameters:
        squad_url: "https://github.com/sciling/qatransfer/releases/download/v0.1/save_class.zip"
        squad_load_path: "/save/out/squad/basic-class/00/save/basic-class-1"
        squad_shared_path: "/save/out/squad/basic-class/00/shared.json"
        run_id: "00"
        sent_size_th: "500"
        ques_size_th: "30"
        num_epochs: "12"
        num_steps: "5000"
        eval_period: "200"
        save_period: "200"
        start_step: 2001
        end_step: 2201